// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
};